#!/usr/bin/env php
<?php

use Aschmelyun\Cleaver\Cleaver;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
}

$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();

$cleaver = new Cleaver(dirname(__FILE__));
$cleaver->build();